### ISSUE TITLE
The Question about single GPU to test the model（run demo_front.py）

### ISSUE THREAD

**Issue by Gatsby23** [maudzung/Super-Fast-Accurate-3D-Object-Detection#5]
Traceback (most recent call last):
  File "demo_front.py", line 47, in <module>
    model.load_state_dict(torch.load(configs.pretrained_path))
  File "/home/robotics/Application/Anaconda/anaconda3/envs/Object_Detection/lib/python3.6/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/robotics/Application/Anaconda/anaconda3/envs/Object_Detection/lib/python3.6/site-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
  File "/home/robotics/Application/Anaconda/anaconda3/envs/Object_Detection/lib/python3.6/site-packages/torch/serialization.py", line 729, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/robotics/Application/Anaconda/anaconda3/envs/Object_Detection/lib/python3.6/site-packages/torch/serialization.py", line 178, in default_restore_location
    result = fn(storage, location)
  File "/home/robotics/Application/Anaconda/anaconda3/envs/Object_Detection/lib/python3.6/site-packages/torch/serialization.py", line 154, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/robotics/Application/Anaconda/anaconda3/envs/Object_Detection/lib/python3.6/site-packages/torch/serialization.py", line 148, in validate_cuda_device
    device=device, device_count=torch.cuda.device_count()))
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.

My device only have one GPU GTX1660 Ti, So, where should I modify the code to successful run the demo_front.py？

**Comment by maudzung** [comment]
Hi @Gatsby23 
I fixed the bug [here](https://github.com/maudzung/Super-Fast-Accurate-3D-Object-Detection/issues/4), please pull the latest code and try again. Thanks for reporting the bug.
